#!/bin/sh
### BEGIN INIT INFO
# Provides:          autonag
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

PIDFILE=/var/run/autonag.pid
LOGFILE=/var/log/autonag.log
DAEMON=/usr/bin/php
DAEMON_IP=0.0.0.0
DAEMON_PORT=8080
DAEMON_SCRIPT=/usr/local/lib/autonag/web/hostConfigBuilder.php

start() {
    if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
        echo 'Service already running' >&2
        return 1
    fi
    echo 'Starting service...' >&2
    local CMD="$DAEMON -S $DAEMON_IP:$DAEMON_PORT $DAEMON_SCRIPT &> \"$LOGFILE\" & echo \$!"
    su -c "$CMD" > "$PIDFILE"
    echo 'Service started' >&2
}

stop() {
    if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
        echo 'Service not running' >&2
        return 1
    fi
    echo 'Stopping service…' >&2
    kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
    echo 'Service stopped' >&2
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
esac
